#!/usr/bin/env python3
"""
run_calibration.py

Commissioning Workflow for the Roman Space Telescope pointing calibration.
Executes two sequential tasks:
  1. WFI Macroscopic Alignment: Solves the "geometric layout" of the 18 SCAs.
  2. FGS Boresight Calibration: Derives the updated Body-to-FGS quaternion
                                using Wahba's problem and the WFI cross-matched
                                star catalogs.
"""

import glob
import json
import os
import warnings
from pathlib import Path

import numpy as np
import pysiaf
import roman_datamodels as rdm
from astropy.table import Table
from scipy.spatial.transform import Rotation as R

# Import the core modules from the unified workflow
from roman_pointing import (
    align_wfi,
    apply_dva_scale_to_catalog,
    calibrate_roman_fgs_alignment,
    export_alignment_to_yaml,
    fetch_local_commissioning_gaia,
)


def load_standalone_matches(output_dir="roman_gaia_match"):
    """
    Reads the 1-to-1 matched star pairs generated by match_roman_gaia.py.
    Returns a dictionary mapping SCA names to arrays of observed pixels and true Gaia coordinates.
    """
    matched_data = {}
    ecsv_files = glob.glob(f"{output_dir}/*_matches.ecsv")

    if not ecsv_files:
        print("No matched catalogs found in the output directory!")
        return None

    for f in ecsv_files:
        det = f.split("/")[-1].split("_")[0]  # Extracts 'WFI01'
        sca_key = f"{det}_FULL" if not det.endswith("_FULL") else det

        t = Table.read(f, format="ascii.ecsv")

        matched_data[sca_key] = {
            "x_obs": np.array(t["x"]),
            "y_obs": np.array(t["y"]),
            "ra_cat": np.array(t["ra_epoch"]),
            "dec_cat": np.array(t["dec_epoch"]),
        }

    print(f"Loaded perfect 1-to-1 matches for {len(matched_data)} SCAs.")
    return matched_data


def load_standalone_matches_as_seed(output_dir="roman_gaia_match"):
    """
    Reads summary JSON files generated by the standalone matcher
    to provide high-confidence initial shifts for alignment.py.
    """
    out_path = Path(output_dir)
    summary_files = list(out_path.glob("*_summary.json"))

    if not summary_files:
        print("No standalone summary files found. Running standard fallback.")
        return None

    precomputed_seeds = {}
    for sf in summary_files:
        with open(sf, "r") as f:
            data = json.load(f)
            det = data.get("detector")
            sca_key = f"{det}_FULL" if not det.endswith("_FULL") else det

            precomputed_seeds[sca_key] = {
                "dx": data.get("dx_center", 0.0),
                "dy": data.get("dy_center", 0.0),
                "affine_coeffs": data.get("affine_offset_coefficients"),
            }

    print(
        f"Loaded pre-computed matches for {len(precomputed_seeds)} SCAs from standalone output."
    )
    return precomputed_seeds


def main():
    # =========================================================================
    # CONFIGURATION & OVERRIDES
    # =========================================================================
    # --- ALIGNMENT MODE ---
    # Set to 4 for Full 4th-Order Polynomials (absorbs DVA).
    # Set to 1 for standard Affine transformations (Scale & Skew only).
    FIT_DEGREE = 4
    # ----------------------

    # --- ALIGNMENT MODE ---
    # Set to 4 for Full 4th-Order Polynomials (absorbs DVA).
    # Set to 1 for standard Affine transformations (Scale & Skew only).
    FIT_DEGREE = 4
    # ----------------------

    # --- BAM TARGET OVERRIDES ---
    # Flight Software BAM coordinates for WFI_CEN
    # Later, this can be parsed directly from the live telemetry quaternion
    # CURRENT_BAM_WFI_CEN = {"V2": 1686.491033, "V3": -1014.335948, "Angle": -60.13916}
    CURRENT_BAM_WFI_CEN = None
    # ----------------------------------

    # Toggle to enable/disable Differential Velocity Aberration (DVA) correction
    # Only turn it off if spacecraft velocities are missing or corrupted.
    apply_dva = True

    # --- MANUAL TELEMETRY OVERRIDES ---
    # Set to a float to override pipeline metadata, or None to read from ASDF.
    MANUAL_RA_V1 = None
    MANUAL_DEC_V1 = None
    MANUAL_PA_V3 = None

    MANUAL_VX_KMS = None
    MANUAL_VY_KMS = None
    MANUAL_VZ_KMS = None

    # Set to a list/tuple of 4 floats to override qbj, or None to calculate from pointing.
    # Example: MANUAL_QBJ = [0.70515723, 0.08269192, -0.68259625, -0.17314064]
    MANUAL_QBJ = None
    # ----------------------------------

    # --- CUSTOM SIAF TOGGLE ---
    CUSTOM_SIAF_PATH = None  # Example: "test_new_siaf.xml"
    # ----------------------------------

    # =========================================================================
    # 1. DATA INGEST & INITIALIZATION
    # =========================================================================
    print("--- 1. DATA INGEST ---")

    if CUSTOM_SIAF_PATH and os.path.exists(CUSTOM_SIAF_PATH):
        base_dir = os.path.dirname(os.path.abspath(CUSTOM_SIAF_PATH))
        file_name = os.path.basename(CUSTOM_SIAF_PATH)
        roman_siaf = pysiaf.Siaf("Roman", basepath=base_dir, filename=file_name)
        print(f"Loaded custom SIAF from: {CUSTOM_SIAF_PATH}")
        active_user_offsets = {
            "d_ra_arcsec": 0.0,
            "d_dec_arcsec": 0.0,
            "d_pa_arcsec": 0.0,
        }
    else:
        roman_siaf = pysiaf.Siaf("Roman")
        print("Loaded default PRD SIAF via pysiaf.")
        active_user_offsets = {
            "d_ra_arcsec": -133.6,
            "d_dec_arcsec": -154.93,
            "d_pa_arcsec": 0.0,
        }

    # Reconstruct the phot_catalogs dictionary from the ECSV files
    ecsv_files = sorted(glob.glob("*_wfi??_f146_cal.asdf_catalog.ecsv"))
    print(f"Found {len(ecsv_files)} extracted catalogs to align.")
    if not ecsv_files:
        print(
            "Error: No *_catalog.ecsv files found. Run batch_extraction.py script first."
        )
        return

    phot_catalogs = {}
    for filepath in ecsv_files:
        basename = os.path.basename(filepath)
        # Parse out the WFI chip ID (e.g., 'WFI01')
        parts = basename.upper().split("_")
        sca_name = next(
            (part for part in parts if part.startswith("WFI") and len(part) == 5), None
        )

        if sca_name:
            dict_key = f"{sca_name}_FULL"
            phot_catalogs[dict_key] = Table.read(filepath, format="ascii.ecsv")
        else:
            print(f"Warning: Could not parse SCA name from {basename}")

    if not phot_catalogs:
        print("Error: No valid catalogs loaded into memory. Exiting.")
        return

    # ---------------------------------------------------------
    # FILTER OBSERVED CATALOGS BY BRIGHTNESS
    # ---------------------------------------------------------
    max_observed_stars = (
        1e9  # Adjust this number to test different cuts (e.g., 100, 300, 500)
    )

    for sca_key, cat in phot_catalogs.items():
        # --- NEW: Spatially mask out the disruptive star cluster on WFI01 ---
        if sca_key == "WFI01_FULL":
            # Plug in your actual center pixel coordinates and radius here
            XC = 2236.0  # Example center X pixel
            YC = 1459.0  # Example center Y pixel
            RADIUS = 300.0  # Example radius in pixels

            # Calculate the distance of every star from the cluster center
            distances = np.hypot(cat["x"] - XC, cat["y"] - YC)

            # Create a mask that keeps everything OUTSIDE the cluster radius
            cluster_mask = distances > RADIUS

            # Overwrite the catalog with the filtered version
            cat = cat[cluster_mask]
            phot_catalogs[sca_key] = cat
            print(
                f"  -> Masked out {np.sum(~cluster_mask)} cluster stars from WFI01."
            )  # --------------------------------------------------------------------

        # Check if a magnitude column exists (common names: 'mag', 'instrumental_mag')
        mag_col = None
        for candidate in ["mag", "instrumental_mag", "phot_g_mean_mag"]:
            if candidate in cat.colnames:
                mag_col = candidate
                break

        if mag_col:
            # Sort by magnitude ascending (brightest stars have the lowest magnitude)
            cat.sort(mag_col)
            if len(cat) > max_observed_stars:
                phot_catalogs[sca_key] = cat[:max_observed_stars]
        elif "flux" in cat.colnames:
            # Fallback: sort by flux descending if magnitude isn't available
            cat.sort("flux", reverse=True)
            if len(cat) > max_observed_stars:
                phot_catalogs[sca_key] = cat[:max_observed_stars]

    print(
        f"  -> Filtered all observed SCA catalogs to the brightest {max_observed_stars} sources per chip."
    )

    # Extract nominal pointing metadata to anchor the reference catalog query
    original_asdfs = glob.glob("*_wfi??_f146_cal.asdf")
    if not original_asdfs:
        print("Error: No original ASDF files found. Cannot extract pointing metadata.")
        return

    original_asdf = original_asdfs[0]
    print(f"\nExtracting reference observation metadata from: {original_asdf}")

    with rdm.open(original_asdf) as f:
        # 1. Pointing Meta (with manual override check)
        try:
            ra_v1 = MANUAL_RA_V1 if MANUAL_RA_V1 is not None else f.meta.pointing.ra_v1
            dec_v1 = (
                MANUAL_DEC_V1 if MANUAL_DEC_V1 is not None else f.meta.pointing.dec_v1
            )
            pa_v3 = MANUAL_PA_V3 if MANUAL_PA_V3 is not None else f.meta.pointing.pa_v3
        except AttributeError:
            print(
                "Error: Pointing metadata missing from ASDF and no manual override provided."
            )
            return

        # 2. DVA Meta
        try:
            dva_scale = f.meta.velocity_aberration.scale_factor
            dva_ra_ref = f.meta.velocity_aberration.ra_reference
            dva_dec_ref = f.meta.velocity_aberration.dec_reference
            has_dva_meta = True
        except AttributeError:
            has_dva_meta = False
            print(
                "Warning: DVA metadata not found in ASDF. DVA correction will NOT be applied."
            )

        # 3. Spacecraft Velocity Meta (with manual override check)
        try:
            v_x = (
                MANUAL_VX_KMS
                if MANUAL_VX_KMS is not None
                else f.meta.ephemeris.velocity_x
            )
            v_y = (
                MANUAL_VY_KMS
                if MANUAL_VY_KMS is not None
                else f.meta.ephemeris.velocity_y
            )
            v_z = (
                MANUAL_VZ_KMS
                if MANUAL_VZ_KMS is not None
                else f.meta.ephemeris.velocity_z
            )
            velocity_kms = np.array([v_x, v_y, v_z])
        except AttributeError:
            print(
                "Error: Spacecraft velocity missing from ASDF meta and no manual override provided."
            )
            return

        # 4. Observation Date
        try:
            obs_date_str = f.meta.observation.date_start
        except AttributeError:
            print(
                "Warning: Observation date missing from ASDF. Defaulting to 2026-09-20T00:00:00"
            )
            obs_date_str = "2026-09-20T00:00:00"

    pointing_info = {"RA_V1": ra_v1, "DEC_V1": dec_v1, "PA_V3": pa_v3}
    print(
        f"Telemetry Pointing: RA={ra_v1:.5f} deg, Dec={dec_v1:.5f} deg, PA={pa_v3:.5f} deg"
    )

    # ---------------------------------------------------------
    # FLIGHT TELEMETRY INGESTION
    # ---------------------------------------------------------
    if MANUAL_QBJ is not None:
        acs_telemetry_qbj = np.array(MANUAL_QBJ)
        print("  -> Using MANUAL OVERRIDE for Telemetry Quaternion (SCF_AC_SDR_QBJ).")
    else:
        # Dynamically calculate qbj from the pointing information
        m_eci2b = pysiaf.utils.rotations.attitude_matrix(0, 0, ra_v1, dec_v1, pa_v3)
        acs_telemetry_qbj = R.from_matrix(m_eci2b.T).as_quat()
        print(
            "  -> Derived Telemetry Quaternion (SCF_AC_SDR_QBJ) directly from pointing metadata."
        )

    # Nominal BAM Telemetry (SCF_AC_FGS_TBL_Qb -> FGS to Body)
    q_b2fgs_nominal = np.array(
        [
            -0.1859673417539929,
            +0.6837984564491885,
            -0.1800546332580956,
            +0.6822141509826322,
        ]
    )
    # ---------------------------------------------------------

    # Load the Gaia DR3 catalog
    try:
        ref_catalog = fetch_local_commissioning_gaia(
            obs_date_str, local_csv_path="gaia_dr3_commissioning_field.ecsv"
        )

        # Sort the reference catalog by Gaia G-band magnitude (ascending order: brightest first)
        ref_catalog.sort("phot_g_mean_mag")

        # Keep only stars brighter than a certain magnitude threshold (e.g., G < 17.5)
        mag_bright = 12.0
        mag_faint = 19.0
        bright_mask = (ref_catalog["phot_g_mean_mag"] <= mag_faint) & (
            ref_catalog["phot_g_mean_mag"] >= mag_bright
        )
        ref_catalog = ref_catalog[bright_mask]
        print(
            f"  -> Filtered reference catalog: {len(ref_catalog)} stars with {mag_bright} < G <= {mag_faint}"
        )

        # --- APPLY DIFFERENTIAL VELOCITY ABERRATION ---
        if apply_dva and has_dva_meta:
            print("  -> Applying Differential Velocity Aberration (DVA) to Gaia...")
            app_ra, app_dec = apply_dva_scale_to_catalog(
                np.asarray(ref_catalog["ra_epoch"]),
                np.asarray(ref_catalog["dec_epoch"]),
                dva_ra_ref,
                dva_dec_ref,
                dva_scale,
            )
            # Overwrite the catalog columns so align_wfi sees the Apparent Sky
            ref_catalog["ra_epoch"] = app_ra
            ref_catalog["dec_epoch"] = app_dec
        # ----------------------------------------------

    except Exception as e:
        print(f"Error loading local Gaia catalog: {e}")
        return

    # =========================================================================
    # 2. WFI MACROSCOPIC ALIGNMENT (Local Geometry)
    # =========================================================================
    print("\n--- 2. RUNNING WFI ALIGNMENT ---")

    calibrated_siaf_params, attitude_results, matched_pairs_log = align_wfi(
        phot_catalogs=phot_catalogs,
        ref_catalog=ref_catalog,
        pointing_info=pointing_info,
        user_offsets=active_user_offsets,
        max_iterations=5,
        debug=False,
        target_wfi_cen=CURRENT_BAM_WFI_CEN,
        roman_siaf=roman_siaf,
        fit_degree=FIT_DEGREE,  # <--- Added to pass the solver mode
    )

    # Export to SIAF YAML
    output_yaml = export_alignment_to_yaml(
        calibrated_siaf_params, output_prefix="calibrated_roman_siaf"
    )

    # Calculate Recovered Deltas
    mean_dec_rad = np.deg2rad(attitude_results["DEC_V1"])
    d_ra_arcsec = (attitude_results["RA_V1"] - ra_v1) * np.cos(mean_dec_rad) * 3600.0
    d_dec_arcsec = (attitude_results["DEC_V1"] - dec_v1) * 3600.0
    d_pa_arcsec = (attitude_results["PA_V3"] - pa_v3) * 3600.0

    print("\n========================================================")
    print("           MEASURED GLOBAL OFFSETS (DELTAS)       ")
    print("========================================================")
    print(f"Δ RA  (V1): {d_ra_arcsec:8.2f} arcsec")
    print(f"Δ Dec (V1): {d_dec_arcsec:8.2f} arcsec")
    print(f"Δ PA  (V3): {d_pa_arcsec:8.2f} arcsec")

    # =========================================================================
    # 3. FGS BORESIGHT CALIBRATION (Spacecraft Geometry)
    # =========================================================================
    print("\n--- 3. RUNNING FGS BORESIGHT CALIBRATION ---")

    # Format the WFI cross-matched stars for the Wahba FGS solver
    ref_stars_radec = np.array([[row[3], row[4]] for row in matched_pairs_log])
    measured_v2_v3 = np.array([[row[7], row[8]] for row in matched_pairs_log])

    print(f"Feeding {len(ref_stars_radec)} cross-matched stars into Wahba's Problem...")

    try:
        # Execute the vectorized Boresight solver using the dynamic or manual telemetry
        q_b2fgs_calibrated = calibrate_roman_fgs_alignment(
            reference_stars_radec=ref_stars_radec,
            measured_v2_v3=measured_v2_v3,
            q_eci2b=R.from_quat(acs_telemetry_qbj).inv().as_quat(),
            v_sc_eci_kms=velocity_kms,
            wfi_cen_aper=roman_siaf["WFI_CEN"],
            q_b2fgs_old=q_b2fgs_nominal,
        )
        print("\n========================================================")
        print("           FGS BORESIGHT CALIBRATION RESULTS             ")
        print("========================================================")
        print(f"Updated BAM Telemetry (SCF_AC_FGS_TBL_Qb):")
        print(
            f"[{q_b2fgs_calibrated[0]:.17f}, {q_b2fgs_calibrated[1]:.17f}, {q_b2fgs_calibrated[2]:.17f}, {q_b2fgs_calibrated[3]:.17f}]"
        )

        # 1. Calculate the rotation required to align Old FGS to New FGS
        q_nom = R.from_quat(q_b2fgs_nominal)
        q_cal = R.from_quat(q_b2fgs_calibrated)
        delta_q = q_cal * q_nom.inv()

        # 2. Project the Boresight Vector (V1 axis: [1, 0, 0])
        v1_nominal = np.array([1, 0, 0])
        v1_calibrated = delta_q.apply(v1_nominal)

        # Calculate the angular separation between the old and new boresight
        cos_theta = np.clip(np.dot(v1_nominal, v1_calibrated), -1.0, 1.0)
        boresight_shift_arcsec = np.degrees(np.arccos(cos_theta)) * 3600.0

        print(f"Total Boresight Shift (V1 Bore): {boresight_shift_arcsec:.3f} arcsec")
        print("--------------------------------------------------------\n")

    except Exception as e:
        print(f"FGS Boresight Calibration failed: {e}")

    print("\n========================================================")
    print("           INTERPRETATION OF RECOVERED DELTAS             ")
    print("========================================================")
    print("The values above are INVERSE CORRECTION VECTORS.")
    print("To nullify observed systematic biases and achieve")
    print("a zero-mean calibrated state, these corrections")
    print("should be applied to the spacecraft configuration.")
    print("")
    print(" - WFI Alignment: Add ΔRA/ΔDec/ΔPA to observation headers.")
    print(" - FGS Boresight: Apply updated BAM (SCF_AC_FGS_TBL_Qb)")
    print("                  quaternion to Flight Software.")
    print("========================================================\n")


if __name__ == "__main__":
    main()
